### ISSUE TITLE
Not able to run this

### ISSUE THREAD

**Issue by yashb042** [decodelabs/idiom#1]
Hello,

I have tried running this code, but not able to.
This is my php file : 

< ?php
use DecodeLabs\Idiom\Parser;

$content = "ss"
echo Metamorph::{'idiom.extended'}($content);
?>

Am I doing something wrong here? When I run this, the code itself gets printed.

**Comment by betterthanclay** [comment]
Hi @yashb042 , it looks like you have a space in your PHP opening tag, so your whole file will just be considered plain text - if you remove that space, it should work.

**Comment by yashb042** [comment]
Great!!! It worked, but the library you have added is still not loading. There's ClassNotFound

Fatal error: Uncaught Error: Class "DecodeLabs\Idiom\Parser" not found in /Users/yash.bansal/workspace/medium/chat-gpt/parse_html.php:13
Stack trace:
#0 {main}
  thrown in /Users/yash.bansal/workspace/medium/chat-gpt/parse_html.php on line 13


POV : First time using PHP for a project and in kind of hurry to just setup something

**Comment by betterthanclay** [comment]
Ah yeah, I missed that first time round - you mixed up the `use` statements from different parts of the readme, you're importing `DecodeLabs\Idiom\Parser` but trying to use the `DecodeLabs\Metamorph` system.

You can either just use the Idiom parser directly:

```php
use DecodeLabs\Idiom\Parser;

$content = "ss";

echo (new Parser())
    ->setExtended(true)
    ->parse($content);
```

Or you can install Metamorph in your project..

```bash
composer require decodelabs/metamorph
```

…and then use that to interface with Idiom like you're trying to do above:

```php
use DecodeLabs\Metamorph;

$content = "ss"
echo Metamorph::{'idiom.extended'}($content);
```

**Comment by yashb042** [comment]
Yeahh my bad, actually I didn't miss. I was using the following code : 

`<?php

use DecodeLabs\Idiom\Parser;

$content = <<<CONTENT
Idiom allows you to write naturally, converting paragraphs, lines and spaces to the relevant HTML elements.

You can include <strong>tags</strong> where necessary.
CONTENT;

echo "yash";

$parser = new Parser();
$parser->setExtended(true);
echo $parser->parse($content);
`

That is not using Metamorph.

**Comment by yashb042** [comment]
I have installed the Idiom/Parser dependency using composer.

There's this composer.json which got created : 

{
    "require": {
        "decodelabs/idiom": "^0.2.1"
    }
}

I have looked all over, not able to find the thing which I missed

**Comment by yashb042** [comment]
And the dependency too, it is downloaded in my local, I'm able to read the file using Intellij, not sure why I'm still getting this NotFound Exception.

How do I run the code?? I'm simply using 
`php file_name.php`

Is this something similar to created JAR required here too?

Also, while digging, came across some term as **psr-4**
I haven't set any path explicitly.

**Comment by betterthanclay** [comment]
Ok, is that PHP file the only one you're loading in your project? If you're using Composer you need to setup the autoloader first as per the Composer docs - https://getcomposer.org/doc/01-basic-usage.md#autoloading

Assuming your vendor dir is in the same place as your PHP file, it should be something like this:

```php
<?php
use DecodeLabs\Idiom\Parser;
require __DIR__ . '/vendor/autoload.php';

$content = 'My content';

echo (new Parser())
    ->setExtended(true)
    ->parse($content);
```

**Comment by yashb042** [comment]
Voila!!! Just arrived on the same conclusion. Thanks @betterthanclay 
First time that got such prompt responses on Github. All the Best for the project.

**Comment by betterthanclay** [comment]
No worries - you might find spending a bit of time with a few tutorials on Composer and PHP dependencies in general will make your life a lot easier as you're bumping up against stuff that can be a pain to learn as you go at the start, but once you have it learned you can just set it and forget it.
